const {test}=require('node:test'), a=require('node:assert/strict'), vue=require('vue')
const {harness,nodes}=require('./commerce-sfc-harness.cjs')
const tick=()=>new Promise(setImmediate)
const key='checkout_fixed_account_7', q='a'.repeat(64)
const surcharge={policy_version:'surcharge-v2-fixed25-equal1',commission_rate:'25.00',amount_diamonds:3,amount_yuan:'0.30',required_players:3,amount_step_diamonds:3,per_person_gross_diamonds:'1.00',per_person_commission_diamonds:'0.25',per_person_net_diamonds:'0.75'}
const refund=(remote_status='unknown')=>({refund_no:'CR-fixture',local_status:'succeeded',base_amount_yuan:'4.00',surcharge_amount_yuan:'0.30',total_amount_yuan:'4.30',remote_status})
const order=(r=refund(),status='已取消')=>({order_no:'order-7',status,total_price:4,checkout:{contract_version:'surcharge-v2',payment_status:'paid',idempotency_key:key,quote_version:q,base_amount_yuan:'4.00',surcharge_amount_yuan:'0.30',total_amount_yuan:'4.30',total_amount_diamonds:'43.0',attempt_id:'attempt-1',surcharge,blockers:[],refund:r}})
const record=()=>({key,quote_version:q,total_amount_yuan:'4.30',surcharge_diamonds:3,required_players:3,order_no:'order-7',status:'unknown',submitted:true,verified:false,attempt_id:'attempt-1'})
function payment(){const h=harness({'@dcloudio/uni-app':{onLoad:f=>h.hooks.load=f,onShow:f=>h.hooks.show.push(f),onHide:f=>h.hooks.hide.push(f),onUnload:f=>h.hooks.unload.push(f)},'@/utils/request':{BASE_URL:'https://fixture.invalid/api'},'@/utils/commerceRelease':{commerceRelease:{orderSurchargeQuoteSupported:true}}}),requests=[],logins=[];h.storage.token='buyer';h.storage.client_profile={id:7};h.storage['surcharge:v2:checkout:7']=record();h.uni.request=o=>requests.push(o);h.uni.login=o=>logins.push(o);h.uni.setStorageSync=(k,v)=>h.storage[k]=v;const C=h.load('src/pages/boss/surcharge-payment/index.vue').default,scope=vue.effectScope(),draw=scope.run(()=>C.setup({},{expose(){}})),tree=()=>nodes(draw({},[])),text=()=>tree().filter(n=>typeof n.children==='string').map(n=>n.children).join('|');return {h,requests,logins,scope,tree,text,async open(reply){h.hooks.load({key});h.hooks.show[0]();await tick();requests.at(-1).success({statusCode:200,data:reply});await tick()}}
}
test('release-first refund parser accepts exact remote stages and rejects forged refund money/status',()=>{
 const h=harness(),{validateCheckout}=h.load('src/api/surchargeCheckout.ts')
 for(const remote of ['not_required','prepared','dispatching','unknown','succeeded'])a.equal(validateCheckout(order(refund(remote)),key).refund.remote_status,remote)
 for(const bad of [{total_amount_yuan:'4.31'},{base_amount_yuan:'3.99'},{surcharge_amount_yuan:'0.29'},{local_status:'pending'},{remote_status:'failed'},{refund_no:''}])a.throws(()=>validateCheckout(order({...refund(),...bad}),key),/退款|格式/)
})
test('release-first actual payment page prioritizes cancelled refund over paid; unknown never claims WeChat refund or offers second POST',async t=>{
 for(const remote of ['not_required','prepared','dispatching','unknown','succeeded']){
  const m=payment();t.after(()=>m.scope.stop());await m.open(order(refund(remote)));a.match(m.text(),/已取消|已退/);a.doesNotMatch(m.text(),/服务端确认已完成合计付款|(?:^|\|)微信已到账/);a.equal(m.tree().find(n=>n.props?.['data-action']==='confirm-combined-payment'),undefined);a.equal(m.requests.filter(x=>x.method==='POST').length,0);a.equal(m.logins.length,0);a.equal(m.h.storage['surcharge:v2:checkout:7'].verified,false)
  if(remote==='unknown')a.match(m.text(),/微信.*未确认|远端.*未确认/)
 }
})
test('release-first earnings real API and page keep two rows by earning id/source, original fish formatting',async t=>{
 const rows=[{id:101,order_no:'same-order',source:'order',surcharge_no:null,package_name:'服务',boss_name:'老板',status:'pending',status_text:'审核中',net_amount:'1.20',gross_amount:'1.50',commission_amount:'0.30',commission_rate:'20.00',review_until:'2026-09-24T00:00:00Z'},{id:102,order_no:'same-order',source:'surcharge',surcharge_no:'SC-102',package_name:'服务',boss_name:'老板',status:'pending',status_text:'审核中',net_amount:'0.75',gross_amount:'1.00',commission_amount:'0.25',commission_rate:'25.00',review_until:'2026-09-24T00:00:00Z'}]
 const paths=[],h=harness({'@/utils/request':{default:{get:async p=>{paths.push(p);if(p.includes('settlements'))return {count:2,results:rows};if(p.includes('withdrawals'))return {count:0,results:[]};return {review_days:3,available_balance:0,min_withdrawal_amount:0.1}}}},'@/utils/client':{isApprovedPlayer:async()=>true},'@/utils/feedback':{toast:()=>{},getErrorMessage:e=>e.message},'@/utils/nav':{replace:()=>{}}}),C=h.load('src/pages/player/earnings/index.vue').default,scope=vue.effectScope(),draw=scope.run(()=>C.setup({},{expose(){}})),tree=()=>nodes(draw({},[]));t.after(()=>scope.stop());await h.hooks.show[0]();await tick();const cards=tree().filter(n=>n.props?.class==='card record-card');a.equal(cards.length,2);a.deepEqual(cards.map(x=>x.key),[101,102]);const text=tree().filter(n=>typeof n.children==='string').map(n=>n.children).join('|');a.match(text,/原单收益/);a.match(text,/加价收益/);a.match(text,/SC-102/);a.match(text,/1\.20/);a.match(text,/0\.75/);a.equal(paths.filter(p=>p.includes('settlements')).length,1)
})
test('release-first candidate explicitly enables only surcharge quote; gift purchase remains server-gated',()=>{
 const h=harness(),release=h.load('src/utils/commerceRelease.ts').commerceRelease;a.equal(release.orderSurchargeQuoteSupported,true);a.equal(release.orderSurchargeReadSupported,false);const C=h.load('src/components/gifts/GiftHost.vue').default;a.ok(C)
})
test('release-first real checkout entry takes backend denied quote, shows reason and sends zero create/payment POST',async t=>{
 const pending=[],http=[],routes=[],h=harness({'@dcloudio/uni-app':{onLoad:f=>h.hooks.load=f,onShow:f=>h.hooks.show.push(f),onHide:f=>h.hooks.hide.push(f),onUnload:f=>h.hooks.unload.push(f)},'@/utils/request':{BASE_URL:'https://fixture.invalid/api',default:{get:async()=>[{id:11,player_count:3,base_price:4,specs:[],name:'真实接口商品'}],post:async()=>{throw Error('unexpected legacy POST')}}},'@/utils/nav':{replace:(...args)=>routes.push(args),go(){},goMain(){}},'@/utils/feedback':{toast(){},getErrorMessage:e=>e.detail||e.message,success(){}}});
 h.storage.token='buyer';h.storage.client_profile={id:7,openid:'fixture-openid',nickname:'老板'};h.uni.request=o=>{http.push(o);pending.push(o)};h.uni.setStorageSync=(k,v)=>h.storage[k]=v
 const C=h.load('src/pages/shop/checkout/index.vue').default,scope=vue.effectScope(),draw=scope.run(()=>C.setup({},{expose(){}})),tree=()=>nodes(draw({},[]));t.after(()=>scope.stop());h.hooks.load({packageId:'11'});await tick();const action=x=>tree().find(n=>n.props?.['data-action']===x);a.ok(action('surcharge-input'))
 action('surcharge-input').props.onInput({detail:{value:'3'}});await new Promise(r=>setTimeout(r,350));a.equal(http.length,1);a.match(http[0].url,/\/boss\/order\/quote$/);a.equal(http[0].data.surcharge_diamonds,3)
 const denied={contract_version:'surcharge-v2',quote_version:q,base_amount_yuan:'4.00',surcharge_amount_yuan:'0.30',total_amount_yuan:'4.30',base_amount_diamonds:'40.0',total_amount_diamonds:'43.0',required_players:3,surcharge,can_submit:false,blockers:['SURCHARGE_LIFECYCLE_UNAVAILABLE']};pending.shift().success({statusCode:200,data:denied});await tick();a.match(tree().filter(n=>typeof n.children==='string').map(n=>n.children).join('|'),/SURCHARGE_LIFECYCLE_UNAVAILABLE/)
 a.equal(action('submit-order').props.disabled,true);await action('submit-order').props.onTap();a.equal(http.filter(x=>x.url.endsWith('/boss/order')||x.url.endsWith('/pay/balance/create')).length,0);a.deepEqual(routes,[])
})
