const {test}=require('node:test'),a=require('node:assert/strict'),{harness}=require('./commerce-sfc-harness.cjs');
const quote={contract_version:'surcharge-v2',base_amount_yuan:'4.00',surcharge_amount_yuan:'0.30',total_amount_yuan:'4.30',base_amount_diamonds:'40.0',total_amount_diamonds:'43.0',required_players:3,quote_version:'a'.repeat(64),surcharge:{policy_version:'surcharge-v2-fixed25-equal1',commission_rate:'25.00',amount_diamonds:3,amount_yuan:'0.30',required_players:3,amount_step_diamonds:3,per_person_gross_diamonds:'1.00',per_person_commission_diamonds:'0.25',per_person_net_diamonds:'0.75'},can_submit:true,blockers:[]};
const checkout={...quote,payment_status:'created',idempotency_key:'key-fixture',attempt_id:null};
const order={order_no:'fixture-order',status:'待支付',total_price:4,checkout};
function setup(){const calls=[],storage={token:'fixture-client',admin_token:'fixture-admin'},h=harness({'@/utils/sessionExpiry':{handleSessionExpiry:()=>null},'@/utils/purchaseAvailability':{getClientPlatform:()=> 'android',isIOSPurchaseEnabled:()=>true}});h.uni.getStorageSync=k=>storage[k];h.uni.setStorageSync=(k,v)=>storage[k]=v;h.uni.request=o=>calls.push(o);return {calls,storage,h,api:h.load('src/api/surchargeCheckout.ts')}}
test('stage2 API original endpoints client only, strict combined checkout and response amount',async()=>{const m=setup(),p=m.api.createSurchargeOrder({...{boss_wechat:'openid',game_id:'room',package_id:11},surcharge_diamonds:3,quote_version:quote.quote_version,idempotency_key:'key-fixture'},quote);a.equal(m.calls[0].url,'https://fixture.invalid/api/boss/order');a.equal(m.calls[0].header.Authorization,'Bearer fixture-client');m.calls[0].success({statusCode:200,data:order});a.equal((await p).checkout.total_amount_yuan,'4.30');const r=m.api.paySurchargeOrder(order);a.equal(m.calls[1].url,'https://fixture.invalid/api/pay/balance/create');a.deepEqual(m.calls[1].data,{order_no:'fixture-order'});m.calls[1].success({statusCode:200,data:{order_no:'fixture-order',payment_no:'fixture-pay',status:'paid',amount:'4.30',balance:'0.00',checkout:{...checkout,payment_status:'paid',attempt_id:'external-id'}}});a.equal((await r).checkout.payment_status,'paid')});
test('stage2 API fail closed on base-only amount, false paid, wrong key, stale token and no admin fallback',async()=>{let m=setup(),p=m.api.paySurchargeOrder(order);m.calls[0].success({statusCode:200,data:{order_no:'fixture-order',amount:'4.00',checkout:{...checkout,payment_status:'paid'}}});await a.rejects(p,/合计|格式/);m=setup();p=m.api.readSurchargeOrderByKey('key-fixture');a.equal(m.calls[0].method,'GET');a.match(m.calls[0].url,/\/boss\/order\/by-key\?idempotency_key=key-fixture$/);m.calls[0].success({statusCode:200,data:{...order,checkout:{...checkout,payment_status:'paid',attempt_id:'external-id'}}});a.equal((await p).checkout.payment_status,'paid');m=setup();p=m.api.readSurchargeOrderByKey('key-fixture');m.storage.token='';m.calls[0].success({statusCode:200,data:order});await a.rejects(p,/登录|会话/);a.equal(m.calls[0].header.Authorization,'Bearer fixture-client');await a.rejects(m.api.readSurchargeOrderByKey('key-fixture'),/登录/);a.equal(m.calls.length,1)});
test('QA exact 25% and equal split quote invariants',async()=>{const m=harness({'@/utils/sessionExpiry':{handleSessionExpiry:()=>null}}),calls=[];m.uni.request=o=>calls.push(o);const api=m.load('src/api/surchargeQuote.ts');for(const change of [{surcharge:{...quote.surcharge,amount_yuan:'0.31'},surcharge_amount_yuan:'0.31',total_amount_yuan:'4.31',total_amount_diamonds:'43.1'},{surcharge:{...quote.surcharge,per_person_commission_diamonds:'0.24',per_person_net_diamonds:'0.76'}},{surcharge:{...quote.surcharge,per_person_gross_diamonds:'2.00',per_person_commission_diamonds:'0.50',per_person_net_diamonds:'1.50'}}]){const p=api.quoteOrderSurcharge({surcharge_diamonds:3});calls.at(-1).success({statusCode:200,data:{...quote,...change}});await a.rejects(p,/报价格式/)}}
);
test('QA hall isolates effective paid from other pending and fully-refunded records; rejects forged net and partial-refund blocker',()=>{const {hallSurcharge}=harness().load('src/utils/surchargePresentation.ts'),s={policy_version:'surcharge-v2-fixed25-equal1',commission_rate:'25.00',required_players:3,paid_diamonds:12,pending_diamonds:0,refunded_diamonds:0,per_person_net_diamonds:'3.00',blockers:[],earnings_withdrawable:false};for(const x of [{pending_diamonds:3},{refunded_diamonds:1}])a.deepEqual(hallSurcharge({required_players:3,surcharge:{...s,...x}}),{wholeOrderDiamonds:12,netDiamonds:'3.00'});for(const x of [{per_person_net_diamonds:'9.99'},{refunded_diamonds:1,blockers:['SURCHARGE_REFUND_REQUIRES_REVIEW']},{paid_diamonds:0,pending_diamonds:3}])a.equal(hallSurcharge({required_players:3,surcharge:{...s,...x}}),null);a.equal(hallSurcharge({required_players:3,surcharge:s}).netDiamonds,'3.00')});
